version: '3.6'

networks:
  srv:

services:
  hits:
    image: tommoulard/hits
    build:
      context: .
      args:
        - 'SITE_ROOT=hits.changme.org'
    restart: always
    networks:
      - 'srv'
    depends_on:
      - 'postgresql'
    ports:
      - '4000:4000'
  postgresql:
    image: postgres
    restart: always
    user: 1000:1000
    networks:
      - 'srv'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - './postgresql/:/var/lib/postgresql/data'

